apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: devops-dojo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: devops-dojo/api:dev
          imagePullPolicy: IfNotPresent
          command: ["/worker"]
          envFrom:
            - configMapRef:
                name: dojo-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dojo-secrets
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
