# ec2-app module (lab 39): the single-server DevOps Dojo host as a reusable unit —
# the same AMI/key/SG/EIP pattern as deploy/terraform/main.tf, parameterized so
# several environments (deploy/terraform/envs/*) can stamp out their own copy.

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# --- SSH key pair (generated by default, bring-your-own via generate_ssh_key=false) ---
resource "tls_private_key" "this" {
  count     = var.generate_ssh_key ? 1 : 0
  algorithm = "ED25519"
}

resource "local_sensitive_file" "private_key" {
  count           = var.generate_ssh_key ? 1 : 0
  content         = tls_private_key.this[0].private_key_openssh
  filename        = var.private_key_path
  file_permission = "0400"
}

resource "aws_key_pair" "this" {
  key_name   = "${var.project_name}-key"
  public_key = var.generate_ssh_key ? tls_private_key.this[0].public_key_openssh : file(var.public_key_path)
}

# SSH from the admin only; HTTP/HTTPS public (Caddy); nothing else exposed.
resource "aws_security_group" "this" {
  name        = "${var.project_name}-sg"
  description = "${var.project_name}: SSH from admin IP, HTTP/HTTPS public."

  ingress {
    description = "SSH (admin only)"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.allowed_ssh_cidr]
  }
  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    description = "HTTPS"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Project = var.project_name }
}

resource "aws_instance" "this" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.this.id]

  root_block_device {
    volume_size = var.root_volume_size
    volume_type = "gp3"
  }

  tags = {
    Name    = var.project_name
    Project = var.project_name
  }
}

resource "aws_eip" "this" {
  instance = aws_instance.this.id
  domain   = "vpc"
  tags     = { Project = var.project_name }
}
