apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          command: ["/worker"]
          envFrom:
            - configMapRef:
                name: dojo-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dojo-secrets
                  key: DATABASE_URL
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
