apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dojo-ai
  namespace: dojo-ai
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-api
                port:
                  number: 8000
